### ISSUE TITLE
Make timeline persistent while scrolling through workstreams

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/dashboard#4]
It would be brilliant if the months / year bar would remain in sight while scrolling through the work of the different workstreams. @jen-martin do you think that's possible?

**Comment by jen-martin** [comment]
Unfortunately, this is a limitation of the Gantt charting library I'm using (Frappe Gantt). There is an open ticket for exactly this feature in their GH repo. :-(

I'll take a look to see if I can find some kind of work-around or custom solution that isn't too onerous. I can also try minimizing the content above and below the chart to maximize the vertical real estate for the chart itself.

**Comment by monicacecilia** [comment]
Ah, I see. Thanks for looking into this, Jen. 
See also these two tickets, #5 and #6, for more ideas on how to help the display issues. 🌷

**Comment by jen-martin** [comment]
Fixed with PR #8, which enhances the Gantt charting app; these enhancements also set the foundation for work on #5 and #6

**Comment by monicacecilia** [comment]
Thank youuu @jen-martin! Fantastic news! 🎉
