### ISSUE TITLE
Toggle Workstreams on / off in dashboard display

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/dashboard#5]
It would be great if we could toggle all the tickets for a specific workstream on/off from the dashboard display.

**Comment by monicacecilia** [comment]
@jen-martin - have you been able to look into the ability to toggle workstreams on / off in our dashboard?

**Comment by jen-martin** [comment]
There are a couple of ways to handle this. The ideal solution will require significant modification to original Frappe Gantt chart app (to handle moving the y-coordinate of all the SVG graphics that are below the hidden group). The less ideal but quick-and-easy option involves re-querying GitHub to include/exclude by workstream. I can definitely have one or the other option done by the end of the quarter.

**Comment by jen-martin** [comment]
Done. PR #9 replaces the text labels at the top with buttons to toggle each work stream's task items on or off.

Note that this iteration of the task viewer no longer displays items without an associated milestone indicating the Phase. (I can add a button to show/hide these items if desired.)
