### ISSUE TITLE
Switch order of 'operations' tickets to last / bottom of display

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/dashboard#6]
Please move the collection of tickets that belong to the Operations workstream to the right / bottom of the dashboard display.

**Comment by monicacecilia** [comment]
@jen-martin  ping! 🔔

**Comment by jen-martin** [comment]
Currently working on this; will definitely have done by end of quarter.

**Comment by jen-martin** [comment]
PR #9 moves the operations tickets to the bottom of the chart. Let me know if you had something else in mind for displaying Operations tasks.

Note that this iteration of the task viewer no longer displays items without an associated milestone indicating the Phase in which it is due, or (for Operations tasks) inferable task start/end date.

**Comment by monicacecilia** [comment]
Thanks, this what I had in mind for the placement of the Operations tickets. 

And thanks for the update on the display of tickets without associated milestones. Technically, every ticket should now be associated to one. Here's hoping. 🤞 😉
